image: Visual Studio 2017
platform: x64

clone_folder: c:\projects\uhk-agent

environment:
  GH_TOKEN:
    secure: 3IebpEKmC39codi1wT6dXx8mql4/mCL1JzZ7lir7GQ5MWRnCxlED2OXbiKHHigDV
  CSC_LINK: c:\projects\uhk-agent\scripts\certs\windows-cert.p12
  matrix:
    - nodejs_version: "12.13.0"

matrix:
  fast_finish: true

build: off

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - node -v
  - npm -v
  - appveyor-retry npm install

test_script:
  - appveyor-retry npm run build
  - npm run lint
  - set CHROME_BIN="C:\Program Files (x86)\Chromium\Application\chrome.exe"
  - npm run test
  - npm run release
